% tidx=find(smp==1 | smp==3 | smp ==5 | smp ==7);
% smp(tidx)=smp(tidx)-1;
% test=sum(smp==2)./size(smp,1);
% match=sum(smp==4)./size(smp,1);
% odor=sum(smp==1 |smp==2|smp==3)./size(smp,1);
both=sum(smp==6| smp==5| smp==7)./size(smp,1);
lick=sum(smp==4)./size(smp,1);
toSave=nan(25,3);
stack=[lick',both'];
toSave(2:end,2:end)=stack;
save('sel2Way.txt','toSave','-ascii');
system('R:\ZX\Tools\gnuplot\bin\gnuplot.exe -persist R:\ZX\APC\RecordingAug16\gnuplotSel2Way.txt');